// <auto-generated />
using System;
using APS8_CSHARP_API.Infra.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APS8_CSHARP_API.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231106233325_Alterado-Locais4")]
    partial class AlteradoLocais4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APS8_CSHARP_API.Domain.Entidades.Local", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CEP")
                        .HasColumnType("int");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataAtualizado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(18, 7)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(18, 7)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Locais");
                });

            modelBuilder.Entity("APS8_CSHARP_API.Domain.Entidades.LocalInformacoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClimaticosJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataAtualizado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriado")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LocalId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("QualidadeArJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocalId");

                    b.ToTable("LocalInformacoes");
                });

            modelBuilder.Entity("APS8_CSHARP_API.Domain.Entidades.LocalInformacoes", b =>
                {
                    b.HasOne("APS8_CSHARP_API.Domain.Entidades.Local", "Local")
                        .WithMany("LocalInformacoes")
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Local");
                });

            modelBuilder.Entity("APS8_CSHARP_API.Domain.Entidades.Local", b =>
                {
                    b.Navigation("LocalInformacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
